apiVersion: v1
kind: Service
metadata:
  name: timingattack-service
  namespace: timing
spec:
  selector:
    app: timingattack
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30011  
  type: NodePort

